// Generated by kit/sfx_pack.py. Do not edit by hand.
export const PACK = {
 "whoosh-fast": {
  "kind": "whoosh",
  "dur": 1.28,
  "hit": 0.6,
  "desc": "quick airy whoosh, the default for things sliding in"
 },
 "whoosh-fast-2": {
  "kind": "whoosh",
  "dur": 0.71,
  "hit": 0.25,
  "desc": "quick whoosh, a little heavier"
 },
 "whoosh-tiny": {
  "kind": "whoosh",
  "dur": 0.42,
  "hit": 0.07,
  "desc": "very short flick, for small labels and chips"
 },
 "whoosh-short": {
  "kind": "whoosh",
  "dur": 0.21,
  "hit": 0.05,
  "desc": "short whoosh"
 },
 "whoosh-mid": {
  "kind": "whoosh",
  "dur": 0.21,
  "hit": 0.05,
  "desc": "medium whoosh"
 },
 "swoosh": {
  "kind": "whoosh",
  "dur": 1.3,
  "hit": 0.5,
  "desc": "swoosh, a bit longer"
 },
 "swoosh-clean": {
  "kind": "whoosh",
  "dur": 0.45,
  "hit": 0.05,
  "desc": "clean fast swoosh"
 },
 "whoosh-soft": {
  "kind": "whoosh",
  "dur": 0.77,
  "hit": 0.23,
  "desc": "soft whoosh with a tail"
 },
 "whoosh-punchy": {
  "kind": "whoosh",
  "dur": 0.75,
  "hit": 0.2,
  "desc": "punchy whoosh, good for scene changes"
 },
 "whoosh-swing": {
  "kind": "whoosh",
  "dur": 0.27,
  "hit": 0.06,
  "desc": "strong swing, for something swung or thrown"
 },
 "whoosh-close": {
  "kind": "whoosh",
  "dur": 1.02,
  "hit": 0.13,
  "desc": "close swing past the mic"
 },
 "whoosh-swing-2": {
  "kind": "whoosh",
  "dur": 0.45,
  "hit": 0.1,
  "desc": "swing whoosh"
 },
 "whoosh-arrow": {
  "kind": "whoosh",
  "dur": 0.26,
  "hit": 0.1,
  "desc": "arrow flying past, for arrows and pointers"
 },
 "arrow": {
  "kind": "whoosh",
  "dur": 2.44,
  "hit": 1.93,
  "desc": "arrow shot and thunk"
 },
 "transition-wind": {
  "kind": "whoosh",
  "dur": 0.93,
  "hit": 0.13,
  "desc": "cinematic wind swoosh, scene change"
 },
 "transition-wind-2": {
  "kind": "whoosh",
  "dur": 0.83,
  "hit": 0.21,
  "desc": "cinematic wind swoosh, scene change"
 },
 "whoosh-metal": {
  "kind": "whoosh",
  "dur": 0.42,
  "hit": 0.07,
  "desc": "whoosh ending in a metallic hit"
 },
 "transition-short": {
  "kind": "whoosh",
  "dur": 0.21,
  "hit": 0.05,
  "desc": "short transition sweep"
 },
 "transition-flare": {
  "kind": "whoosh",
  "dur": 0.67,
  "hit": 0.2,
  "desc": "bright shimmer sweep, light flare"
 },
 "transition-fire": {
  "kind": "whoosh",
  "dur": 3.89,
  "hit": 0.16,
  "desc": "fiery whoosh transition"
 },
 "whoosh-long": {
  "kind": "whoosh",
  "dur": 8.0,
  "hit": 3.46,
  "desc": "long whoosh (cut to 8 s)"
 },
 "zoom-in-out": {
  "kind": "whoosh",
  "dur": 0.86,
  "hit": 0.12,
  "desc": "zoom in and out, for camera zooms"
 },
 "warp-slide": {
  "kind": "whoosh",
  "dur": 0.84,
  "hit": 0.19,
  "desc": "warping slide, for something morphing"
 },
 "rewind-tape": {
  "kind": "whoosh",
  "dur": 1.73,
  "hit": 0.24,
  "desc": "fast tape rewind, for going back"
 },
 "rewind": {
  "kind": "whoosh",
  "dur": 2.07,
  "hit": 1.51,
  "desc": "rewind sound"
 },
 "fast-forward": {
  "kind": "whoosh",
  "dur": 1.92,
  "hit": 0.75,
  "desc": "fast forward"
 },
 "fast-forward-2": {
  "kind": "whoosh",
  "dur": 2.61,
  "hit": 0.85,
  "desc": "fast forward, cartoonish"
 },
 "portal": {
  "kind": "whoosh",
  "dur": 1.38,
  "hit": 0.83,
  "desc": "sci-fi portal hop, teleport"
 },
 "riser-short": {
  "kind": "riser",
  "dur": 1.65,
  "hit": 1.38,
  "desc": "short build-up (about 2 s) into a reveal"
 },
 "riser-ascend": {
  "kind": "riser",
  "dur": 3.02,
  "hit": 2.68,
  "desc": "ascending tone, things going up"
 },
 "riser-whoosh": {
  "kind": "riser",
  "dur": 2.22,
  "hit": 2.15,
  "desc": "building whoosh into a hit"
 },
 "suspense-sting": {
  "kind": "riser",
  "dur": 1.08,
  "hit": 0.09,
  "desc": "sudden suspense sting"
 },
 "swell-brass": {
  "kind": "riser",
  "dur": 8.0,
  "hit": 3.39,
  "desc": "big brassy swell, trailer-style build"
 },
 "riser-drums": {
  "kind": "riser",
  "dur": 8.0,
  "hit": 7.05,
  "desc": "robotic drum riser, long build (cut to 8 s)"
 },
 "power-up": {
  "kind": "riser",
  "dur": 2.44,
  "hit": 0.54,
  "desc": "electric power-up"
 },
 "drum-roll": {
  "kind": "riser",
  "dur": 3.09,
  "hit": 0.67,
  "desc": "drum roll, before announcing a number"
 },
 "boom-short": {
  "kind": "impact",
  "dur": 1.13,
  "hit": 0.28,
  "desc": "short boom, punchy"
 },
 "boom": {
  "kind": "impact",
  "dur": 6.5,
  "hit": 0.21,
  "desc": "deep boom with a tail"
 },
 "boom-deep": {
  "kind": "impact",
  "dur": 4.07,
  "hit": 0.12,
  "desc": "very deep sub boom"
 },
 "impact": {
  "kind": "impact",
  "dur": 3.77,
  "hit": 0.05,
  "desc": "cinematic impact"
 },
 "hit-grand": {
  "kind": "impact",
  "dur": 4.15,
  "hit": 0.09,
  "desc": "grand orchestral hit"
 },
 "hit-grand-2": {
  "kind": "impact",
  "dur": 4.38,
  "hit": 0.2,
  "desc": "grand orchestral hit, second take"
 },
 "subsonic": {
  "kind": "impact",
  "dur": 5.43,
  "hit": 0.18,
  "desc": "subsonic drop, felt more than heard"
 },
 "subsonic-2": {
  "kind": "impact",
  "dur": 5.86,
  "hit": 0.61,
  "desc": "subsonic drop"
 },
 "boom-universe": {
  "kind": "impact",
  "dur": 6.57,
  "hit": 0.05,
  "desc": "huge spacey boom, the biggest reveal"
 },
 "boom-universe-2": {
  "kind": "impact",
  "dur": 5.72,
  "hit": 0.62,
  "desc": "huge spacey boom"
 },
 "slam-metal": {
  "kind": "impact",
  "dur": 6.14,
  "hit": 1.1,
  "desc": "metal slam, a door shutting"
 },
 "struck-down": {
  "kind": "impact",
  "dur": 2.9,
  "hit": 0.29,
  "desc": "heavy downward hit"
 },
 "hit-low": {
  "kind": "impact",
  "dur": 2.46,
  "hit": 0.87,
  "desc": "quick low hit"
 },
 "drop-dark": {
  "kind": "impact",
  "dur": 8.0,
  "hit": 6.57,
  "desc": "dark drop, the bad news"
 },
 "drop-sub": {
  "kind": "impact",
  "dur": 3.87,
  "hit": 0.1,
  "desc": "distorted sub drop"
 },
 "bass-drop": {
  "kind": "impact",
  "dur": 3.78,
  "hit": 1.23,
  "desc": "bass drop"
 },
 "boom-brass": {
  "kind": "impact",
  "dur": 4.18,
  "hit": 0.31,
  "desc": "brass boom"
 },
 "boom-shot": {
  "kind": "impact",
  "dur": 3.61,
  "hit": 0.23,
  "desc": "boom shot"
 },
 "boom-metal": {
  "kind": "impact",
  "dur": 3.93,
  "hit": 0.17,
  "desc": "boom with metallic ring"
 },
 "impact-cinematic": {
  "kind": "impact",
  "dur": 4.9,
  "hit": 1.41,
  "desc": "big cinematic impact"
 },
 "impact-space": {
  "kind": "impact",
  "dur": 3.27,
  "hit": 0.02,
  "desc": "spacey impact"
 },
 "hit-glass-suspense": {
  "kind": "impact",
  "dur": 3.83,
  "hit": 0.04,
  "desc": "glassy suspense hit"
 },
 "boom-trailer": {
  "kind": "impact",
  "dur": 8.0,
  "hit": 0.09,
  "desc": "trailer boom (cut to 8 s)"
 },
 "thud-heavy": {
  "kind": "impact",
  "dur": 1.06,
  "hit": 0.07,
  "desc": "heavy object landing"
 },
 "hit-swell": {
  "kind": "impact",
  "dur": 3.22,
  "hit": 0.45,
  "desc": "swell into a hit"
 },
 "punch": {
  "kind": "impact",
  "dur": 0.55,
  "hit": 0.06,
  "desc": "punch"
 },
 "splat": {
  "kind": "impact",
  "dur": 0.32,
  "hit": 0.05,
  "desc": "cartoon splat"
 },
 "click-mouse": {
  "kind": "click",
  "dur": 0.2,
  "hit": 0.02,
  "desc": "single mouse click, short"
 },
 "click-mouse-2": {
  "kind": "click",
  "dur": 0.2,
  "hit": 0.02,
  "desc": "mouse click"
 },
 "click-mouse-3": {
  "kind": "click",
  "dur": 0.17,
  "hit": 0.11,
  "desc": "mouse click"
 },
 "click": {
  "kind": "click",
  "dur": 0.19,
  "hit": 0.12,
  "desc": "UI click"
 },
 "click-2": {
  "kind": "click",
  "dur": 0.21,
  "hit": 0.02,
  "desc": "click"
 },
 "click-3": {
  "kind": "click",
  "dur": 0.2,
  "hit": 0.02,
  "desc": "click"
 },
 "click-soft": {
  "kind": "click",
  "dur": 0.33,
  "hit": 0.01,
  "desc": "soft click"
 },
 "click-soft-2": {
  "kind": "click",
  "dur": 0.23,
  "hit": 0.01,
  "desc": "soft click"
 },
 "click-soft-3": {
  "kind": "click",
  "dur": 0.3,
  "hit": 0.02,
  "desc": "soft click"
 },
 "click-hard": {
  "kind": "click",
  "dur": 0.13,
  "hit": 0.05,
  "desc": "hard pop click"
 },
 "key-press": {
  "kind": "click",
  "dur": 0.21,
  "hit": 0.04,
  "desc": "one keyboard key"
 },
 "key-futuristic": {
  "kind": "click",
  "dur": 0.8,
  "hit": 0.44,
  "desc": "futuristic metal key press"
 },
 "menu-select": {
  "kind": "click",
  "dur": 0.47,
  "hit": 0.12,
  "desc": "game menu select blip"
 },
 "click-mech": {
  "kind": "click",
  "dur": 0.69,
  "hit": 0.59,
  "desc": "mechanical click (gun click)"
 },
 "click-metal": {
  "kind": "click",
  "dur": 0.82,
  "hit": 0.73,
  "desc": "metal click"
 },
 "switch": {
  "kind": "click",
  "dur": 0.61,
  "hit": 0.14,
  "desc": "switch flipped"
 },
 "message": {
  "kind": "click",
  "dur": 0.67,
  "hit": 0.18,
  "desc": "message notification"
 },
 "popup": {
  "kind": "click",
  "dur": 0.13,
  "hit": 0.01,
  "desc": "pop-up notification"
 },
 "notify-idea": {
  "kind": "click",
  "dur": 1.22,
  "hit": 0.06,
  "desc": "new-idea notification chime"
 },
 "pop": {
  "kind": "pop",
  "dur": 0.13,
  "hit": 0.01,
  "desc": "short pop, default for icons appearing"
 },
 "pop-2": {
  "kind": "pop",
  "dur": 0.25,
  "hit": 0.02,
  "desc": "pop"
 },
 "pop-3": {
  "kind": "pop",
  "dur": 2.46,
  "hit": 0.02,
  "desc": "pop"
 },
 "pop-bubble": {
  "kind": "pop",
  "dur": 0.18,
  "hit": 0.02,
  "desc": "bubble pop"
 },
 "pop-4": {
  "kind": "pop",
  "dur": 0.27,
  "hit": 0.03,
  "desc": "pop"
 },
 "bloop": {
  "kind": "pop",
  "dur": 0.25,
  "hit": 0.04,
  "desc": "cartoon bloop"
 },
 "cork": {
  "kind": "pop",
  "dur": 0.15,
  "hit": 0.03,
  "desc": "bottle cork pop"
 },
 "typing": {
  "kind": "typing",
  "dur": 8.0,
  "hit": 1.37,
  "desc": "keyboard typing (cut to 8 s)"
 },
 "typing-2": {
  "kind": "typing",
  "dur": 6.58,
  "hit": 6.43,
  "desc": "keyboard typing (cut to 8 s)"
 },
 "typewriter": {
  "kind": "typing",
  "dur": 3.66,
  "hit": 2.69,
  "desc": "typewriter"
 },
 "writing": {
  "kind": "typing",
  "dur": 1.2,
  "hit": 0.17,
  "desc": "pen writing"
 },
 "writing-2": {
  "kind": "typing",
  "dur": 2.78,
  "hit": 1.47,
  "desc": "pen writing"
 },
 "pencil": {
  "kind": "typing",
  "dur": 0.48,
  "hit": 0.35,
  "desc": "pencil stroke"
 },
 "paper-flip": {
  "kind": "typing",
  "dur": 0.69,
  "hit": 0.39,
  "desc": "paper flip, page turn"
 },
 "paper-slide": {
  "kind": "typing",
  "dur": 0.7,
  "hit": 0.16,
  "desc": "paper sliding across a table"
 },
 "paper-rip": {
  "kind": "typing",
  "dur": 0.63,
  "hit": 0.09,
  "desc": "paper ripping"
 },
 "paper-crumple": {
  "kind": "typing",
  "dur": 1.79,
  "hit": 0.14,
  "desc": "paper crumpled"
 },
 "glitch": {
  "kind": "tech",
  "dur": 1.74,
  "hit": 0.25,
  "desc": "digital glitch"
 },
 "glitch-2": {
  "kind": "tech",
  "dur": 1.2,
  "hit": 0.11,
  "desc": "digital glitch"
 },
 "glitch-terminal": {
  "kind": "tech",
  "dur": 2.54,
  "hit": 0.04,
  "desc": "terminal glitch"
 },
 "processing": {
  "kind": "tech",
  "dur": 1.01,
  "hit": 0.22,
  "desc": "computer processing"
 },
 "dial-up": {
  "kind": "tech",
  "dur": 2.69,
  "hit": 0.87,
  "desc": "dial-up modem"
 },
 "rf-switch": {
  "kind": "tech",
  "dur": 1.77,
  "hit": 0.11,
  "desc": "radio switching"
 },
 "data-erased": {
  "kind": "tech",
  "dur": 1.36,
  "hit": 1.14,
  "desc": "data erased"
 },
 "reboot-fail": {
  "kind": "tech",
  "dur": 5.19,
  "hit": 0.76,
  "desc": "reboot failure"
 },
 "line-break": {
  "kind": "tech",
  "dur": 2.56,
  "hit": 0.62,
  "desc": "signal line break"
 },
 "data-transfer": {
  "kind": "tech",
  "dur": 1.45,
  "hit": 0.62,
  "desc": "data transfer chatter"
 },
 "access-denied": {
  "kind": "tech",
  "dur": 4.29,
  "hit": 0.4,
  "desc": "access denied"
 },
 "access-granted": {
  "kind": "tech",
  "dur": 1.56,
  "hit": 0.38,
  "desc": "access granted"
 },
 "intermod": {
  "kind": "tech",
  "dur": 3.22,
  "hit": 1.48,
  "desc": "electronic intermodulation hum"
 },
 "disc-read": {
  "kind": "tech",
  "dur": 1.53,
  "hit": 0.63,
  "desc": "disc reading"
 },
 "network-connect": {
  "kind": "tech",
  "dur": 1.55,
  "hit": 0.23,
  "desc": "network connected"
 },
 "disconnected": {
  "kind": "tech",
  "dur": 2.24,
  "hit": 0.27,
  "desc": "disconnected"
 },
 "download": {
  "kind": "tech",
  "dur": 2.19,
  "hit": 0.27,
  "desc": "download"
 },
 "loading": {
  "kind": "tech",
  "dur": 8.0,
  "hit": 0.53,
  "desc": "UI data loading (cut to 8 s)"
 },
 "hacking": {
  "kind": "tech",
  "dur": 8.0,
  "hit": 6.36,
  "desc": "hacking beeps (cut to 8 s)"
 },
 "counting-digital": {
  "kind": "tech",
  "dur": 5.18,
  "hit": 3.24,
  "desc": "digital counter running"
 },
 "digits": {
  "kind": "tech",
  "dur": 1.96,
  "hit": 1.42,
  "desc": "digital display digits"
 },
 "digits-2": {
  "kind": "tech",
  "dur": 2.06,
  "hit": 0.98,
  "desc": "digital display digits"
 },
 "digits-3": {
  "kind": "tech",
  "dur": 2.0,
  "hit": 1.11,
  "desc": "digital display digits"
 },
 "digits-4": {
  "kind": "tech",
  "dur": 2.08,
  "hit": 0.6,
  "desc": "digital display digits"
 },
 "energy-shot": {
  "kind": "tech",
  "dur": 3.75,
  "hit": 1.09,
  "desc": "light energy shot"
 },
 "censor": {
  "kind": "tech",
  "dur": 0.3,
  "hit": 0.21,
  "desc": "censor beep"
 },
 "censor-2": {
  "kind": "tech",
  "dur": 0.31,
  "hit": 0.02,
  "desc": "censor beep, short"
 },
 "cash-register": {
  "kind": "money",
  "dur": 1.05,
  "hit": 0.48,
  "desc": "cash register"
 },
 "kaching": {
  "kind": "money",
  "dur": 1.16,
  "hit": 0.13,
  "desc": "ka-ching"
 },
 "cash-register-2": {
  "kind": "money",
  "dur": 1.41,
  "hit": 0.12,
  "desc": "cash register"
 },
 "purchase": {
  "kind": "money",
  "dur": 1.44,
  "hit": 0.32,
  "desc": "purchase ka-ching"
 },
 "cash-ting": {
  "kind": "money",
  "dur": 1.2,
  "hit": 0.13,
  "desc": "short cash ting"
 },
 "ding": {
  "kind": "result",
  "dur": 1.24,
  "hit": 0.07,
  "desc": "ding, a number landing"
 },
 "ding-short": {
  "kind": "result",
  "dur": 0.38,
  "hit": 0.02,
  "desc": "short ding"
 },
 "correct": {
  "kind": "result",
  "dur": 1.23,
  "hit": 0.07,
  "desc": "correct answer"
 },
 "win": {
  "kind": "result",
  "dur": 0.68,
  "hit": 0.09,
  "desc": "quick win jingle"
 },
 "idea": {
  "kind": "result",
  "dur": 1.82,
  "hit": 0.31,
  "desc": "good idea"
 },
 "wrong": {
  "kind": "result",
  "dur": 0.89,
  "hit": 0.2,
  "desc": "wrong answer buzz"
 },
 "shatter": {
  "kind": "result",
  "dur": 0.94,
  "hit": 0.02,
  "desc": "glass shattering, a belief breaking"
 },
 "bell-boxing": {
  "kind": "result",
  "dur": 4.28,
  "hit": 0.62,
  "desc": "boxing bell"
 },
 "party-horn": {
  "kind": "result",
  "dur": 0.85,
  "hit": 0.08,
  "desc": "party horn"
 },
 "clock": {
  "kind": "time",
  "dur": 8.0,
  "hit": 2.42,
  "desc": "clock ticking (cut to 8 s)"
 },
 "clock-fast": {
  "kind": "time",
  "dur": 8.0,
  "hit": 6.63,
  "desc": "fast clock ticking (cut to 8 s)"
 },
 "clock-2": {
  "kind": "time",
  "dur": 8.0,
  "hit": 4.6,
  "desc": "clock ticking (cut to 8 s)"
 },
 "gears": {
  "kind": "time",
  "dur": 8.0,
  "hit": 5.16,
  "desc": "gears turning (cut to 8 s)"
 },
 "shutter": {
  "kind": "camera",
  "dur": 0.31,
  "hit": 0.11,
  "desc": "camera shutter"
 },
 "shutter-2": {
  "kind": "camera",
  "dur": 0.39,
  "hit": 0.02,
  "desc": "camera shutter"
 },
 "shutter-3": {
  "kind": "camera",
  "dur": 0.47,
  "hit": 0.02,
  "desc": "camera shutter"
 },
 "shutter-4": {
  "kind": "camera",
  "dur": 0.47,
  "hit": 0.02,
  "desc": "camera shutter"
 },
 "shutter-5": {
  "kind": "camera",
  "dur": 0.59,
  "hit": 0.4,
  "desc": "camera shutter"
 },
 "flash": {
  "kind": "camera",
  "dur": 0.71,
  "hit": 0.21,
  "desc": "camera flash"
 },
 "flash-2": {
  "kind": "camera",
  "dur": 0.63,
  "hit": 0.16,
  "desc": "camera flash"
 },
 "shutter-6": {
  "kind": "camera",
  "dur": 0.29,
  "hit": 0.08,
  "desc": "shutter click"
 },
 "crowd-gasp": {
  "kind": "people",
  "dur": 1.14,
  "hit": 0.44,
  "desc": "crowd gasps"
 },
 "crowd-aww": {
  "kind": "people",
  "dur": 1.51,
  "hit": 0.26,
  "desc": "crowd awww"
 },
 "kids-yay": {
  "kind": "people",
  "dur": 3.75,
  "hit": 0.7,
  "desc": "kids cheering"
 },
 "hmm": {
  "kind": "people",
  "dur": 0.73,
  "hit": 0.1,
  "desc": "thinking hmmm"
 },
 "applause": {
  "kind": "people",
  "dur": 8.0,
  "hit": 2.11,
  "desc": "applause (cut to 8 s)"
 },
 "wind-spooky": {
  "kind": "misc",
  "dur": 4.82,
  "hit": 1.8,
  "desc": "spooky wind"
 },
 "heartbeat": {
  "kind": "misc",
  "dur": 8.0,
  "hit": 0.23,
  "desc": "heartbeat (cut to 8 s)"
 },
 "incoming-crash": {
  "kind": "misc",
  "dur": 8.0,
  "hit": 0.54,
  "desc": "incoming crash (cut to 8 s)"
 },
 "drop-brass": {
  "kind": "misc",
  "dur": 8.0,
  "hit": 3.77,
  "desc": "brassy drop (cut to 8 s)"
 },
 "boom-feedback": {
  "kind": "misc",
  "dur": 6.76,
  "hit": 0.16,
  "desc": "boom with feedback"
 },
 "whistle": {
  "kind": "misc",
  "dur": 1.05,
  "hit": 0.16,
  "desc": "cartoon toy whistle"
 },
 "wheel-spin": {
  "kind": "misc",
  "dur": 8.0,
  "hit": 0.99,
  "desc": "wheel spinning (cut to 8 s)"
 },
 "projector": {
  "kind": "misc",
  "dur": 8.0,
  "hit": 0.03,
  "desc": "film projector running (cut to 8 s)"
 }
} as const;
export type PackName = keyof typeof PACK;
